### ISSUE TITLE
No Crate?

### ISSUE THREAD

**Issue by dyc3** [icewind1991/steam-vent#1]
Hey I was looking to automate some Tf2 item stuff, and in order to craft metal you need to send the correct protobuf message to tf2's game coordinator. I was wondering if you were planning to put this up as a crate? You already have `steam-vent-proto` and `steam-vent-crypto` published.

**Comment by icewind1991** [comment]
This crate isn't in a usable state atm

**Comment by dumbasPL** [comment]
will it ever be?

**Comment by icewind1991** [comment]
It's closer to being usable now and you can probably build some stuff around it. But I would like to do some more restructuring before publishing a first version.

**Comment by icewind1991** [comment]
0.1 is published

**Comment by dyc3** [comment]
Can you create a git tag and github release for it? It helps to know exactly what code is in the 0.1 release.

**Comment by icewind1991** [comment]
done
