### ISSUE TITLE
`Connection` doesn't release heartbeat infinite loop on drop

### ISSUE THREAD

**Issue by johnpyp** [icewind1991/steam-vent#16]
It looks like `Connection` doesn't respect RAII semantics in the case of its heartbeat loop. The loop will run forever in the background as it's just created by a naked `spawn` which doesn't have an exit condition.

So, in a program which may initialize multiple connections and drop them at various points, there's no way to actually cleanup this naked connection loop.

A very simple way to fix this would just be to add the join handle to a private field in the connection struct, so Rust's join glue will automatically clean it up.

**Comment by ported-pw** [comment]
> A very simple way to fix this would just be to add the join handle to a private field in the connection struct, so Rust's join glue will automatically clean it up.

The task will not be cancelled when the `JoinHandle` is dropped, see https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html#cancel-safety. Also, the `JoinHandle` is not cloneable.

I've added a PR that fixes the issue using `CancellationToken`. Getting the `AbortHandle`, storing that and calling `abort` would also be an option.

**Comment by johnpyp** [comment]
Ah right, yeah it was AbortHandle I was thinking of. Great, thanks!
