### ISSUE TITLE
Listen to messages before auth

### ISSUE THREAD

**Issue by xnxkzeu** [icewind1991/steam-vent#24]
I'm trying to implement generation of Steam Auth Ticket, and right now there is no way to read CMsgClientGameConnectTokens that client receives after logging in
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let server_list = ServerList::discover().await?;

    let connection = Connection::login(
        &server_list,
        "some_username",
        "some_password",
        FileGuardDataStore::user_cache(),
        ConsoleAuthConfirmationHandler::default().or(DeviceConfirmationHandler),
    )
    .await?;

    let mut tokens_messages = connection.on::<CMsgClientGameConnectTokens>();
    let mut game_tokens = VecDeque::new();

    spawn(async move {
        while let Some(Ok(tokens_message)) = tokens_messages.next().await {
            for token in tokens_message.tokens.into_iter() {
                game_tokens.push_back(token);
            }

            let max_tokens = tokens_message.max_tokens_to_keep.unwrap_or(10) as usize;
            let remove_tokens = game_tokens.len() - max_tokens;

            if remove_tokens > 0 {
                game_tokens.drain(..remove_tokens);
            }
        }
    });

    loop {}
}
```

That code actually does work, but only if your connection is very slow, and message arrives after `tokens_messages` stream is created

**Comment by icewind1991** [comment]
132935966cf3914061c646a4b1520b366ce54c52 allows accessing messages that didn't get handled by any filter.

The api isn't great but it does support this use case, see the added example.

**Comment by xnxkzeu** [comment]
Thank you, works good to me

**Comment by icewind1991** [comment]
As part of making authentication more flexible, it's now possible to start listening on a connection before doing the authentication, making this use case a lot simpler. See the updates example from d6c6e3a
