### ISSUE TITLE
CS2 GC Integration

### ISSUE THREAD

**Issue by DarkGL** [icewind1991/steam-vent#4]
I would love to see support to something similar like in this package

https://github.com/DoctorMcKay/node-globaloffensive

especially `inspectItem`

something like that was already done for TF2 here https://github.com/juliarose/steam-vent

I'm willing to donate to support work on this feature if you are interested in that

**Comment by icewind1991** [comment]
GC integration is now implemented and the csgo protos have been added.

You should now be able to implement this I think, see the [tf2 backpack example](https://github.com/icewind1991/steam-vent/blob/main/examples/backpack.rs) for how to use the gc.

**Comment by DarkGL** [comment]
Thank you, shouldn't there be new release?

**Comment by icewind1991** [comment]
released with 0.3.0
